export const ACTION_TYPE = {
//user action
  LOGIN : 'LOGIN',
  REGISTER : 'REGISTER',
  CHANGE_PASSWORD : 'CHANGE_PASSWORD',
  UPDATE_INFO_USER : 'UPDATE_INFO_USER',
  LIST_USER: 'LIST_USER',
  CREATE_USER: 'CREATE_USER',
  DELETE_USER: 'DELETE_USER',
  PROFILE: 'PROFILE',

// content
  CREATE_CONTENT_PROVIDER: 'CREATE_CONTENT_PROVIDER',
  LIST_CONTENT_PROVIDER: 'LIST_CONTENT_PROVIDER',
  LIST_CONTENT: 'LIST_CONTENT',
  EDIT_CONTENT: 'EDIT_CONTENT',
  CONTENT_PROVIDER: 'CONTENT_PROVIDER',
  DELETE_CONTENT_PROVIDER: 'DELETE_CONTENT_PROVIDER',
  EDIT_CONTENT_PROVIDER: 'EDIT_CONTENT_PROVIDER',

//instream Ads
  INSTREAM_ADS: 'INSTREAM_ADS',
  LIST_INSTREAM_ADS: 'LIST_INSTREAM_ADS',
  LIST_ALL_INSTREAM_ADS: 'LIST_ALL_INSTREAM_ADS',
  DELETE_INSTREAM_ADS_ID: 'DELETE_INSTREAM_ADS_ID',
  EDIT_INSTREAM_ADS_ID: 'EDIT_INSTREAM_ADS_ID',
  LIST_INSTREAM_ADS_ID: 'LIST_INSTREAM_ADS_ID',

// set Token
  SET_TOKEN: 'SET_TOKEN',

//popup
  OPEN_POPUP: 'OPEN_POPUP',
  CLOSE_POPUP: 'CLOSE_POPUP'

}

export const createAction = (type, data) => {
	return {type, data}
}
