
export const POPUP = {
	NAME: {
		USER: {
			DELETE_USER: "DELETE_USER",
			EDIT_USER: "EDIT_USER",
			LOGOUT: 'LOGOUT'
		},
		IN_STREAM_ADS: {
			CREATE_INSTREAM_ADS: 'CREATE_INSTREAM_ADS',
			CREATE_NEW_INSTREAM_ADS: 'CREATE_NEW_INSTREAM_ADS',
			DELETE_INSTREAM_ADS: 'DELETE_INSTREAM_ADS',
			DUPLICATE_INSTREAM_ADS: 'DUPLICATE_INSTREAM_ADS',
			EDIT_INSTREAM_ADS: 'EDIT_INSTREAM_ADS'
		},
		CONTENT: {
			EDIT_CONTENT: 'EDIT_CONTENT',
			ADD_CONTENT: 'ADD_CONTENT'
		},
		LIVE_EVENT: {
			DELETE_LIVE_ITEM: 'DELETE_LIVE_ITEM',
			EDIT_LIVE_ITEM: 'EDIT_LIVE_ITEM',
		}
	},
}

