
export const POPUP = {
	NAME: {
		CUSTOMER: {
			DELETE_CUSTOMER: "DELETE_CUSTOMER",
			UPDATE_CUSTOMER: "UPDATE_CUSTOMER",
			LOGOUT: "LOGOUT",
			CREATE_CUSTOMER: "CREATE_CUSTOMER",
		},
		IN_STREAM_ADS: {
			CREATE_INSTREAM_ADS: 'CREATE_INSTREAM_ADS',
			CREATE_NEW_INSTREAM_ADS: 'CREATE_NEW_INSTREAM_ADS',
			DELETE_INSTREAM_ADS: 'DELETE_INSTREAM_ADS',
			DUPLICATE_INSTREAM_ADS: 'DUPLICATE_INSTREAM_ADS',
			EDIT_INSTREAM_ADS: 'EDIT_INSTREAM_ADS'
		},
		CONTENT: {
			EDIT_CONTENT: 'EDIT_CONTENT',
			ADD_CONTENT: 'ADD_CONTENT'
		},
		LIVE_EVENT: {
			DELETE_LIVE_ITEM: "DELETE_LIVE_ITEM",
			EDIT_LIVE_ITEM: "EDIT_LIVE_ITEM",
			CREATE_LIVE_ENTITY:"CREATE_LIVE_ENTITY",
		}
	},
}

