

const CUSTOMER = {
    EMAIL: "Email",
    PASSWORD: 'Password',
    OLD_PASSWORD: 'Password Old',
    CREATE_CUSTOMER: "Tạo Customer",
    INVALID_EMAIL: "Email không hợp lệ",
    INVALID_PASSWORD: "Mật khẩu phải chứa số, kí tự đặt biệt và tối đa từ 6-15 kí tự",
    CUSTOMER_LIST: "Customers List",
    REGISTER: "Register Customer",
    CREATE_ACCOUNT: "Create Account",
    DELETE_CUSTOMER: "Xóa Customer",
    DELETE_CUSTOMER_CURRENT: "Bạn có muốn xóa người dùng này ?",
    LOGOUT: "Đăng xuất",
    LOGIN: "Login",
    MANAGE_CUSTOMER: "Quản lí Customer",
    NOT_ACTIVE_CUSTOMER: "Chưa Active",
    ACTIVE_CUSTOMER: "Active",
    LOCK_CUSTOMER: "Lock",
    DELETE: "Delete",
    PERMISSION_STATUS: "Bạn không có quyền thay đổi trạng thái",
    UPDATE_INFO_CUSTOMER: "Update Info",
    UPDATE_SUCCESS: "Cập nhật thành công",
    CREATE_SUCCESS: "Tạo Customer thành công",
}
const LIVE = {
    LIVE_EVENT_MANAGE_LIST: "Live Event Management List",
    CREATE_LIVE_ENTITY: "Tạo Live Entity",
    NAME_LIVE_ENTITY: "Nhập tên Live Entity",
    DESCRIPTION_INFO: "Thông tin thêm",
    IMPORT_DESCRIPTION_INFO: "Nhập thông tin thêm",
    IMPORT_NAME_LIVE_ENTITY: "Vui lòng nhập tên Live Entity",
    LIVE_EVENT_INFO: "Thông tin sự kiện",
    DELETE_EVENT: "Xóa sự kiện",
    BLOCK_EVENT: "Block sự kiện",
    RELOAD_EVENT: "Reload sự kiện",
    DELETE_EVENT_CURRENT: "Bạn có muốn xóa sự kiện này ?",
    BLOCK_EVENT_CURRENT: "Bạn có muốn block sự kiện này ?",
    RELOAD_EVENT_CURRENT: "Bạn có muốn reload sự kiện này ?",
    DVR: "Dvr",
    PRESET_ID: "Preset_id",
    REPLAY: "Replay",
    NAME_RELAY: "Nhập tên Relay",
    URL_RELAY: "Nhập Url Relay",
    KEY_RELAY: "Nhập Key Relay",
    ERR_RELAY: "Nhập đầy đủ các thông tin relay hoặc để trống",
    ADD_RELAY: "+ Add",
    ADD_RELAY_TITLE: "Thêm Relay",
    EDIT_RELAY_TITLE: "Chỉnh sữa Relay",
    DELETE_RELAY: 'Xóa Relay',
    DELETE_RELAY_TITLE: 'Bạn có muốn xóa Relay này ?',
    ERR_CHARACTER_LIMIT: "Vui lòng nhập tên và mô tả từ 3 kí tự trở lên, tối đa 100 kí tự. !",
    PERMISSION_BLOCK: "Bạn không có quyền Block sự kiện",
    BLOCK_SUCCESS: "Sự kiện đã bị khoá",
    DELETE_SUCCESS: "Xoá sự kiện thành công",
    CREATE_SUCCESS: "Tạo sự kiện thành công"
}
const GENERAL = {
    STATUS: "Thông báo",
    MANAGE: "Quản lý",
    EDIT: "Chỉnh sửa",
    EDIT_STATUS: "Edit Status",
    DELETE: "Xoá",
    AFTER: "Sau",
    BEFORE: "Trước",
    SAVE: "Lưu",
    NAME: "Tên",
    BLOCK: "Block",
    RELOAD: "Reload",
    RELAY: "Relay",
    UPDATE_SUCCESS: "Cập nhật thành công",
}
module.exports = {
    CUSTOMER,
    LIVE,
    GENERAL
}
