
export default {
    // action
    GET: "GET",
    SET: "SET",
    REMOVE: "REMOVE",
    CLEAR: "CLEAR",

    // keys
    CONTENT_PROVIDER:'CONTENT_PROVIDER',
    FIRST_LOGIN: "FIRST_LOGIN",
    TRIAL_APP: "TRIAL_APP",
    USER_GUEST: "USER_GUEST",
    RE_LOGIN: "RE_LOGIN",
    LOGIN: "LOGIN",
    DEVICE_ID: "DEVICE_ID",
    ID_CONTENT_PROVIDER: 'ID_CONTENT_PROVIDER',

}
